# permissions for end users to view bars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bar-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sample-operator
    app.kubernetes.io/part-of: sample-operator
    app.kubernetes.io/managed-by: kustomize
  name: bar-viewer-role
rules:
- apiGroups:
  - sample.redhat.com
  resources:
  - bars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample.redhat.com
  resources:
  - bars/status
  verbs:
  - get
