# permissions for end users to edit bars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bar-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sample-operator
    app.kubernetes.io/part-of: sample-operator
    app.kubernetes.io/managed-by: kustomize
  name: bar-editor-role
rules:
- apiGroups:
  - sample.redhat.com
  resources:
  - bars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.redhat.com
  resources:
  - bars/status
  verbs:
  - get
